ageKL/objects/Challenge__c.object
<CustomObject>
    <description>Challenge in Game Engine</description>
    <label>Challenge</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Challenges</pluralLabel>
    <recordTypes>
        <fullName>Challenge</fullName>
        <active>true</active>
        <description>Base Challenge</description>
        <label>Challenge</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ageKL/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>pse__Salesforce_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Salesforce User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Game_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>Settings for the Appirio Gamification Engine (AGE).</description>
    <fields>
        <fullName>Challenge_Million_Biller__c</fullName>
        <description>Employees that have logged &gt;1M in timecards for fixed fee and/or T&amp;M.</description>
        <inlineHelpText>Employees that have logged &gt;1M in timecards for fixed fee and/or T&amp;M.</inlineHelpText>
        <label>Challenge - Million Biller</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Game Settings</label>
</CustomObject>

ageKL/objects/Points__c.object
<CustomObject>
    <description>Earned or spent Points per user.</description>
    <fields>
        <fullName>Awarded_From_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>User that awarded the Points.  This is used to check Points Bucket.</description>
        <inlineHelpText>User that awarded the Points.  This is used to check Points Bucket.</inlineHelpText>
        <label>Awarded From Id</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Points</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Challenge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Challenge that the user has completed to earn points</description>
        <inlineHelpText>Challenge that the user has completed to earn points</inlineHelpText>
        <label>Challenge</label>
        <referenceTo>Challenge__c</referenceTo>
        <relationshipLabel>Points</relationshipLabel>
        <relationshipName>Earned_Points</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Target_Record_Id__c</fullName>
        <description>For Earned Points: the Id of the Object that references the Points that were awarded.

For Transferred Points: the Id of the Object to WHERE the points were transferred to.</description>
        <inlineHelpText>For Earned Points: the Id of the Object that references the Points that were awarded.

For Transferred Points: the Id of the Object to WHERE the points were transferred to.</inlineHelpText>
        <label>Target Record Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>User that has earned the Challenge points</description>
        <inlineHelpText>User that has earned the Challenge points</inlineHelpText>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Earned_Points</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Points</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Points</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ageKL/classes/AwardMillionBillerTest.cls
@istest(SeeAllData=true)
class AwardMillionBillerTest {

// (c) Appirio 2014
//
// Test class to test awarding employees that have billed > 1M in their time cards.
// Had to use 'SeeAllData=true' because there were so many downstream SOQL inserts
// to test and I was hitting the governor.  
//
// 03/14/2014     Kym Le              Original
// 07/13/2014     Glenn Weinstein     Commenting out testMillionBillerPositive() - it is painfully slow due to the
//                                    SOQL query.  It's taking 490 seconds!!!
//

  public static testmethod void testMillionBillerPositive(){  
    /*
    User u = AGETestUtility.CreateTestUser();
    System.runAs(u) { 
    
      String targetRecordId = Game_Settings__c.getInstance().Challenge_Million_Biller__c;
      Id resourceId;
    
      Test.startTest();
    
        //query the database for an employee that has reached > 1M
        List<AggregateResult> timeCards = [SELECT   pse__Resource__r.Name, 
                                                    pse__Resource__r.Id, 
                                                    SUM(T_M_Equivalent_Revenue__c) 
                                           FROM     pse__Timecard_Header__c 
                                           GROUP BY pse__Resource__r.Id, 
                                                    pse__Resource__r.Name 
                                           HAVING   SUM(T_M_Equivalent_Revenue__c) > 1000000 Limit 1];
                                         
        resourceId = (Id)timeCards[0].get('Id');          
          
        //call the award method from the AwardMillionBiller class    
        AwardMillionBiller.execute(timeCards);   
      
        //get the userId based on the resourceId
        Contact awardedContact = [SELECT pse__Salesforce_User__c
                                  FROM   Contact
                                  WHERE  Id = :resourceId];
                                
        //get the list of points for the user and narrow down the query based on the targetRecordId of
        //the MillionBiller challenge
        List<Points__c> points = new List<Points__c>([SELECT Id, 
                                                             Target_Record_Id__c, 
                                                             User__c, 
                                                             Challenge__c 
                                                      FROM   Points__c 
                                                      WHERE  User__c = :awardedContact.pse__Salesforce_User__c
                                                      AND    Target_Record_Id__c = :targetRecordId]); 
  
        //the user should have been awarded the points for the challenge  
        System.AssertEquals(1, points.size());                                                                     
    
      Test.stopTest();  
    }
    */
  }
  
  /*
  public static testmethod void testMillionBillerNegativeDoubleAward(){
    
    User u = AGETestUtility.CreateTestUser();
    System.runAs(u) { 
    
      String targetRecordId = Game_Settings__c.getInstance().Challenge_Million_Biller__c;
      Id resourceId;
    
      Test.startTest();
    
        //query the database for an employee that has reached > 1M
        List<AggregateResult> timeCards = [SELECT   pse__Resource__r.Name, 
                                                    pse__Resource__r.Id, 
                                                    SUM(T_M_Equivalent_Revenue__c) 
                                           FROM     pse__Timecard_Header__c 
                                           GROUP BY pse__Resource__r.Id, 
                                                    pse__Resource__r.Name 
                                           HAVING   SUM(T_M_Equivalent_Revenue__c) > 1000000 Limit 1];
                                         
        resourceId = (Id)timeCards[0].get('Id');     
        
        Challenge__c c = [SELECT Id FROM Challenge__c WHERE Name = :targetRecordId];     
                            
        //get the userId based on the resourceId      
        Contact awardedContact = [SELECT pse__Salesforce_User__c
                                  FROM   Contact
                                  WHERE  Id = :resourceId];

        //create a points record for the user and this particular challenge by the targetRecordId                            
        Points__c testPoints = new Points__c(User__c = awardedContact.pse__Salesforce_User__c, Target_Record_ID__c = targetRecordId,
                                             Challenge__c = c.Id, Awarded_From_Id__c = UserInfo.getUserId()); 
        insert testPoints;
      
        //call the award method from the AwardMillionBiller class        
        AwardMillionBiller.execute(timeCards);         
                                
        //get the list of points for the user and narrow down the query based on the targetRecordId of
        //the MillionBiller challenge
        List<Points__c> points = new List<Points__c>([SELECT Id, 
                                                             Target_Record_Id__c, 
                                                             User__c, 
                                                             Challenge__c 
                                                      FROM   Points__c 
                                                      WHERE  User__c = :awardedContact.pse__Salesforce_User__c
                                                      AND    Target_Record_Id__c = :targetRecordId]); 
        
        //the user should have been awarded only ONCE for the challenge 
        System.AssertEquals(1, points.size());                                                                     
    
      Test.stopTest();  
    }
  } */
  
}