src/objects/Awarded_Badge__c.object
<CustomObject>
    <description>Represents the awarding of a particular Badge to a particular User.</description>
    <fields>
        <fullName>Badge__c</fullName>
        <label>Badge</label>
        <referenceTo>Badge__c</referenceTo>
        <relationshipLabel>Awarded To</relationshipLabel>
        <relationshipName>Awarded_Badges</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <description>Date in which the Awarded Badge is effective</description>
        <label>Effective Date</label>
        
        <type>Date</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Awarded_Badges</relationshipName>
        
        <type>Lookup</type>
    </fields>
    <label>Awarded Badge</label>
    <nameField>
        <displayFormat>AB-{00000}</displayFormat>
        <label>Awarded Badge Name</label>
        
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Awarded Badges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Badge__c.object
<CustomObject>
    <description>Badges that are obtained by completed specified Challenge(s)</description>
    <fields>
        <fullName>Image_URL__c</fullName>
        <description>URL for image associated to Badge</description>
        <inlineHelpText>URL for image associated to Badge</inlineHelpText>
        <label>Image URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>The date that the Badge becomes active.</description>
        <inlineHelpText>The date that the Badge becomes active.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>Title for the Badge</description>
        <inlineHelpText>Title for the Badge</inlineHelpText>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Badge</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Badges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Challenge__c.object
<CustomObject>
    <description>Challenge in Game Engine</description>
    <fields>
        <fullName>Start_Date__c</fullName>
        <defaultValue>today()</defaultValue>
        <description>The date that the Challenge becomes active.</description>
        <inlineHelpText>The date that the Challenge becomes active.</inlineHelpText>
        <label>Start Date</label>
        
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>Title for the Challenge</description>
        <inlineHelpText>Title for the Challenge</inlineHelpText>
        <label>Title</label>
        <length>255</length>
        
        <type>Text</type>
    </fields>
    <label>Challenge</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Name</label>
        
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Challenges</pluralLabel>
    <recordTypes>
        <fullName>Challenge</fullName>
        <active>true</active>
        <description>Base Challenge</description>
        <label>Challenge</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Game_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>Settings for the Appirio Gamification Engine (AGE).</description>
    <fields>
        <fullName>Chatter_Group_ID_All_Activities__c</fullName>
        <description>Sobject ID of the Chatter Group to which all activity notifications should be posted.</description>
        <inlineHelpText>Sobject ID of the Chatter Group to which all activity notifications should be posted.</inlineHelpText>
        <label>Chatter Group ID - All Activities</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Game Settings</label>
</CustomObject>

src/objects/Points__c.object
<CustomObject>
    <description>Earned or spent Points per user.</description>
    <fields>
        <fullName>Amount__c</fullName>
        <description>Amount of Points</description>
        <inlineHelpText>Amount of Points</inlineHelpText>
        <label>Amount</label>
        <precision>5</precision>
        <scale>0</scale>
        
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Challenge_Title__c</fullName>
        <formula>Challenge__r.Title__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Challenge Title</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Challenge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Challenge that the user has completed to earn points</description>
        <inlineHelpText>Challenge that the user has completed to earn points</inlineHelpText>
        <label>Challenge</label>
        <referenceTo>Challenge__c</referenceTo>
        <relationshipLabel>Points</relationshipLabel>
        <relationshipName>Earned_Points</relationshipName>
        
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>today()</defaultValue>
        <description>Effective date, i.e. the date the points were actually earned.</description>
        <inlineHelpText>Effective date, i.e. the date the points were actually earned.</inlineHelpText>
        <label>Effective Date</label>
        
        <type>Date</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>User that has earned the Challenge points</description>
        <inlineHelpText>User that has earned the Challenge points</inlineHelpText>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Earned_Points</relationshipName>
        
        <type>Lookup</type>
    </fields>
    <label>Points</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Name</label>
        
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Points</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>AGE_Profile_Quote__c</fullName>
        <description>Quote that appear on AGE Profile page</description>
        <inlineHelpText>Quote that appear on AGE Profile page</inlineHelpText>
        <label>AGE Profile Quote</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Facebook_URL__c</fullName>
        <description>Synced automatically from the corresponding PSA Contact record.  Do not update directly on the User record.</description>
        <inlineHelpText>Synced automatically from the corresponding PSA Contact record.  Do not update directly on the User record.</inlineHelpText>
        <label>Facebook URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Full_Name__c</fullName>
        <description>First name plus last name.  Formula field.</description>
        <formula>FirstName &amp; &quot; &quot; &amp; LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>First name plus last name.  Formula field.</inlineHelpText>
        <label>Full Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LinkedIn_URL__c</fullName>
        <description>Synced automatically from the corresponding PSA Contact record.  Do not update directly on the User record.</description>
        <inlineHelpText>Synced automatically from the corresponding PSA Contact record.  Do not update directly on the User record.</inlineHelpText>
        <label>LinkedIn URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Employee Start Date</description>
        <inlineHelpText>Employee Start Date</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Twitter_URL__c</fullName>
        <description>Synced automatically from the corresponding PSA Contact record.  Do not update directly on the User record.</description>
        <inlineHelpText>Synced automatically from the corresponding PSA Contact record.  Do not update directly on the User record.</inlineHelpText>
        <label>Twitter URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/AgeProfileManagerController.cls
public class AgeProfileManagerController extends AgeUserController {

//
// (c) Appirio 
//
// Appirio's Gamification App
//    This controller allows users to enter in their completed challenges and 
//    collect the points earned associated to such challenge
//
// 7/30/13     Kym Le     Original
//

  public String user;
  
  Double lastThrityDayPoint;
  
  //S-161785 Display Badges Count
  public Map<Id,Integer> badgeCount {get;set;}
  
  public AgeProfileManagerController() { 
  
    // URL parameter may specify a particular user for the profile
    user = ApexPages.CurrentPage().getParameters().get('userId');
  
    // otherwise, profile should  default to the current user
    if (user == null) user = UserInfo.getUserId();
    
  }
  
  public String getDisplayUserTimeZone() {
    
    String timeZoneShort = '';
  
    User user = [SELECT TimeZoneSIDKey 
                 FROM   User 
                 WHERE  Id = :user];
                 
    TimeZone userTimeZone = TimeZone.getTimeZone(user.TimeZoneSIDKey);
    String timeZoneName = userTimeZone.getDisplayName();
  
    List<String> timeZoneParts = timeZoneName.split(' ');
      
    for (String s : timeZoneParts) {
      String firstLetter = s.substring(0,1);
      timeZoneShort += firstLetter;
    }
    
    return timeZoneShort;
  }
  
  public User getDisplayUser(){
  
    return [SELECT Name,
                   CompanyName,
                   Title,
                   City,
                   State,
                   Country,
                   Facebook_URL__c,
                   LinkedIn_URL__c,
                   Twitter_URL__c,
                   AGE_Profile_Quote__c,
                   Start_Date__c,
                   Email,
                   Phone,
                   MobilePhone,
                   TimeZoneSidKey,
                   Manager.Name,
                   FullPhotoUrl,
                   SmallPhotoUrl
            FROM   User 
            WHERE  Id = :user];
  }

  public Decimal getTotalPoints(){
    
    AggregateResult[] totalPointsEarned = [SELECT SUM(Amount__c) points
                                           FROM   Points__c
                                           WHERE  User__r.Id = :user 
                                           AND    RecordType.Name = 'Earned Points'
                                           AND    Amount__c > 0];
    
    if (totalPointsEarned[0].get('points')==null) {
      return 0;
    } else {                                              
      return (Decimal)totalPointsEarned[0].get('points');
    }                                                     
  }
  
  public Decimal getQuarterPoints(){
    
    AggregateResult[] quarterPointsEarned = [SELECT SUM(Amount__c) points
                                             FROM   Points__c
                                             WHERE  User__r.Id = :user 
                                             AND    Amount__c > 0
                                             AND    RecordType.Name = 'Earned Points'
                                             AND    Date__c = THIS_QUARTER];
                                
    if (quarterPointsEarned[0].get('points')==null) {
      return 0;
    } else {                                              
      return (Decimal)quarterPointsEarned[0].get('points');
    }                            
  }
  
  
  public List<Points__c> getPoints() {
    return [SELECT   Id,
                     Challenge__c,
                     Challenge_Title__c,
                     CreatedDate
            FROM     Points__c
            WHERE    User__r.Id = :user
            AND      Amount__c > 0
            AND      Challenge__c != ''
            ORDER BY CreatedDate DESC
            LIMIT 5];
  }
  
  
  public Decimal getLastThirtyDaysPoints(){    
    
    AggregateResult[] last30DaysPointsEarned = [SELECT SUM(Amount__c) points
                                                FROM   Points__c
                                                WHERE  User__r.Id = :user 
                                                AND    Amount__c > 0
                                                AND    RecordType.Name = 'Earned Points'
                                                AND    Date__c = LAST_N_DAYS:30];  
                                                     
    if (last30DaysPointsEarned[0].get('points')==null) {
      lastThrityDayPoint =0;
      return 0;
    } else {
      lastThrityDayPoint = (Double)last30DaysPointsEarned[0].get('points');                                            
      return (Decimal)last30DaysPointsEarned[0].get('points');
    }
  }
  
  /* adding leader board ahead user  :- 1 place ahead */
  public User getUserAheadInLeaderBoard(){
  		AggregateResult[] last30DaysPointsEarned = [SELECT SUM(Amount__c) points,user__c
                                                	FROM   Points__c
                                                	WHERE  Amount__c > 0
                                                	AND    RecordType.Name = 'Earned Points'
                                                	AND    Date__c = LAST_N_DAYS:30
                                                	AND    User__r.Id != :user 
                                                	GROUP By user__c
                                                	HAVING SUM(Amount__c) >=: lastThrityDayPoint
                                                   ];  
  	   // let us find the user with one step ahead
  	   Decimal minValue= 0;
  	   String id;
  	   for(AggregateResult r:last30DaysPointsEarned){
  	   		if (r.get('points')==null) continue;
  	   		Decimal pts = (Decimal)r.get('points');
  	   		if(minValue ==0 || pts < minValue){
  	   			minValue =pts;
  	   			id = (String)r.get('user__c');
  	   		}
  	   }
  	   
  	   
  	  return getUser(id);
  }
  
  private User getUser(String id){
  	List<User> u= [Select Id,FullPhotoUrl,Full_Name__c,Name,SmallPhotoURL FROM User WHERE id=:id];
  	return u.size()==0 ? null : u[0];
  }
  
  /* adding leader board ahead user  :- 1 place behind */
  public User getUserBehindInLeaderBoard(){
  		AggregateResult[] last30DaysPointsEarned = [SELECT SUM(Amount__c) points,User__c
                                                	FROM   Points__c
                                                	WHERE  Amount__c > 0
                                                	AND    RecordType.Name = 'Earned Points'
                                                	AND    Date__c = LAST_N_DAYS:30
                                                	AND    User__r.Id != :user 
                                                	GROUP By user__c
                                                	HAVING SUM(Amount__c) <=: lastThrityDayPoint
                                                   ];  
  	   // let us find the user with one step ahead
  	   Decimal maxValue= 0;
  	   String id;
  	   for(AggregateResult r:last30DaysPointsEarned){
  	   		if (r.get('points')==null) continue;
  	   		Decimal pts = (Decimal)r.get('points');
  	   		if(maxValue ==0 || pts > maxValue){
  	   			maxValue =pts;
  	   			id = (String)r.get('User__c');
  	   		}
  	   }
  	   return getUser(id);
  }
  
  //updated the method for chall :- S-161785 Display Badges Count
  public List<Badge__c> getBadges() {
    List<Badge__c> badgeUrl = new List<Badge__c>();
    badgeCount = new Map<Id,Integer>();
   
    //@added the order by to sort latest to older
    List<Awarded_Badge__c> badges = [SELECT 
                   Badge__r.Image_Url__c, Badge__c,
                   Badge__r.Title__c
            FROM   Awarded_Badge__c           
            WHERE  User__r.Id = :user 
            ORDER BY Effective_Date__c DESC];
           
    for(Awarded_Badge__c ab : badges) {
      Integer cnt = badgeCount.get(ab.Badge__c)!=null ? badgeCount.get(ab.Badge__c):0; 
      
      //if we have already added the badge then just increment the count
      if(badgeCount.get(ab.Badge__c)!=null){
      	badgeCount.put(ab.Badge__c,cnt+1); 
      	continue; 
      }
      
      Badge__c awardedBadge = new Badge__c();
      awardedBadge.id=ab.Badge__c;
      awardedBadge.Title__c = ab.Badge__r.Title__c;
      awardedBadge.Image_Url__c = ab.Badge__r.Image_Url__c;
      badgeUrl.add(awardedBadge);
      badgeCount.put(ab.Badge__c,cnt+1); 
           
    }
    
    if (badgeUrl.size() < 4) {
      Integer countTo = 4 - badgeUrl.size();
      
      for (integer i = 0; i < countTo; i++){
        Badge__c badge = new Badge__c();
        badge.Image_Url__c = '/resource/1378764846000/AgeResources/i/badges/badge-3.jpg';
        badgeUrl.add(badge);
      }
    }
    
    return badgeUrl;
  }
  
  
  
  public String getChatterURL() {
    String staticURL = 'https://chattereverywhere-staging.herokuapp.com/client/base/?instance_url=';
    String appEnvironmentURL = URL.getSalesforceBaseUrl().toExternalForm();
    String staticAccessTokenURL = '&access_token=';
    String sessionId = UserInfo.getSessionId();
    String staticGroupText = '#/groups/';
    String chatterGroupId = Game_Settings__c.getInstance().Chatter_Group_ID_All_Activities__c;
    String chatterButtonOptions = '?refreshbtn&linkbtn&notify&gallery';
    
    
    return staticURL + appEnvironmentURL + staticAccessTokenURL + sessionId + staticGroupText + chatterGroupId + chatterButtonOptions;
  }

}