src/objects/Challenge__c.object
<CustomObject>
    <description>Challenge in Game Engine</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Status of Challenge.</description>
        <inlineHelpText>Status of Challenge.</inlineHelpText>
        <label>Active</label>
        
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Archived__c</fullName>
        <description>A challenge that has been inactive for over 1 year.</description>
        <formula>Days_Inactive__c &gt; 365</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>A challenge that has been inactive for over 1 year.</inlineHelpText>
        <label>Archived</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Automated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicator if the Challenge is awarded automatically</description>
        <inlineHelpText>Indicator if the Challenge is awarded automatically</inlineHelpText>
        <label>Automated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Core_Value__c</fullName>
        <description>Core Value associated to the Challenge</description>
        <inlineHelpText>Core Value associated to the Challenge</inlineHelpText>
        <label>Core Value</label>
        <picklist>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fun</fullName>
            </picklistValues>
        </picklist>
        
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description of the Challenge</description>
        <inlineHelpText>Description of the Challenge</inlineHelpText>
        <label>Description</label>
        
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <defaultValue>date(year(today())+1, month(today()), day(today()))</defaultValue>
        <description>Date the Challenge ends</description>
        <inlineHelpText>Date the Challenge ends</inlineHelpText>
        <label>End Date</label>
        
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Ended_in_Last_Year__c</fullName>
        <formula>(Days_Inactive__c &gt; 30) &amp;&amp; (Days_Inactive__c &lt; 365)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Ended in Last Year</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Focus__c</fullName>
        <description>Focus associated to Challenge</description>
        <inlineHelpText>Focus associated to Challenge</inlineHelpText>
        <label>Focus</label>
        <picklist>
            <picklistValues>
                <fullName>Anniversaries</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assets</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awards</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Continuing Ed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recognition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recruiting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shoutouts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Silver Lining</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Topcoder</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Hashtag__c</fullName>
        <description>Hashtag to indicate the Challenge</description>
        <inlineHelpText>Hashtag phrase.  Do not include the &quot;#&quot; symbol.</inlineHelpText>
        <label>Hashtag</label>
        <length>255</length>
        
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Max_Number_of_Achievements_Per_User__c</fullName>
        <description>Maximum number of times a particular user can achieve this Challenge.</description>
        <inlineHelpText>Maximum number of times a particular user can achieve this Challenge.</inlineHelpText>
        <label>Max Number of Achievements Per User</label>
        <precision>3</precision>
        <scale>0</scale>
        
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Recently_Ended__c</fullName>
        <description>A challenge that has been de-activated in the past 30 days.</description>
        <formula>Days_Inactive__c &gt;= 1 &amp;&amp; Days_Inactive__c &lt;= 30</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>A challenge that has been de-activated in the past 30 days.</inlineHelpText>
        <label>Recently Ended</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reward_Points__c</fullName>
        <description>Points awarded to the user upon completion of the Challenge</description>
        <inlineHelpText>Points awarded to the user upon completion of the Challenge</inlineHelpText>
        <label>Reward Points</label>
        <precision>5</precision>
        <scale>0</scale>
        
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <defaultValue>today()</defaultValue>
        <description>The date that the Challenge becomes active.</description>
        <inlineHelpText>The date that the Challenge becomes active.</inlineHelpText>
        <label>Start Date</label>
        
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>Title for the Challenge</description>
        <inlineHelpText>Title for the Challenge</inlineHelpText>
        <label>Title</label>
        <length>255</length>
        
        <type>Text</type>
    </fields>
    <label>Challenge</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Name</label>
        
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Challenges</pluralLabel>
    <recordTypes>
        <fullName>Challenge</fullName>
        <active>true</active>
        <description>Base Challenge</description>
        <label>Challenge</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Challenge_Points_Bucket__c.object
<CustomObject>
    <description>Junction object, representing the M:N relationship between Challenges and Points Buckets.</description>
    <fields>
        <fullName>Challenge__c</fullName>
        <label>Challenge</label>
        <referenceTo>Challenge__c</referenceTo>
        <relationshipLabel>Points Buckets</relationshipLabel>
        <relationshipName>Challenge_Points_Buckets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Points_Bucket__c</fullName>
        <label>Points Bucket</label>
        <referenceTo>Points_Bucket__c</referenceTo>
        <relationshipLabel>Challenges</relationshipLabel>
        <relationshipName>Challenge_Points_Buckets</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Challenge Points Bucket</label>
    <nameField>
        <displayFormat>CPB-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Challenge Points Buckets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Points__c.object
<CustomObject>
    <description>Earned or spent Points per user.</description>
    <fields>
        <fullName>Amount__c</fullName>
        <description>Amount of Points</description>
        <inlineHelpText>Amount of Points</inlineHelpText>
        <label>Amount</label>
        <precision>5</precision>
        <scale>0</scale>
        
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Challenge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Challenge that the user has completed to earn points</description>
        <inlineHelpText>Challenge that the user has completed to earn points</inlineHelpText>
        <label>Challenge</label>
        <referenceTo>Challenge__c</referenceTo>
        <relationshipLabel>Points</relationshipLabel>
        <relationshipName>Earned_Points</relationshipName>
        
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>today()</defaultValue>
        <description>Effective date, i.e. the date the points were actually earned.</description>
        <inlineHelpText>Effective date, i.e. the date the points were actually earned.</inlineHelpText>
        <label>Effective Date</label>
        
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Points_Bucket__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Points Bucket</label>
        <referenceTo>Points_Bucket__c</referenceTo>
        <relationshipLabel>Points</relationshipLabel>
        <relationshipName>Points</relationshipName>
        
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <description>Where the points are coming from.</description>
        <inlineHelpText>Where the points are coming from.</inlineHelpText>
        <label>Source</label>
        <picklist>
            <picklistValues>
                <fullName>Challenge Completed</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Manager Bucket</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Points Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>User that has earned the Challenge points</description>
        <inlineHelpText>User that has earned the Challenge points</inlineHelpText>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Earned_Points</relationshipName>
        
        <type>Lookup</type>
    </fields>
    <label>Points</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Name</label>
        
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Points</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Points_Bucket__c.object
<CustomObject>
    <description>Funding source of a Challenge</description>
    <fields>
        <fullName>Current_Balance__c</fullName>
        <description>Current balance of the Points Bucket</description>
        <inlineHelpText>Current balance of the Points Bucket</inlineHelpText>
        <label>Current Balance</label>
        <precision>18</precision>
        <scale>0</scale>
        
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Owner of the Points Bucket</description>
        <inlineHelpText>Owner of the Points Bucket</inlineHelpText>
        <label>Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Points_Buckets</relationshipName>
        
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        
        <type>Text</type>
    </fields>
    <label>Points Bucket</label>
    <nameField>
        <displayFormat>PB-{0000}</displayFormat>
        <label>Name</label>
        
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Points Buckets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Employee Start Date</description>
        <inlineHelpText>Employee Start Date</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

src/classes/ChallengeManagerController.cls
public class ChallengeManagerController extends AgeUserController {

//
// (c) Appirio 
//
// Appirio's Gamification App
//    This controller allows users to enter in their completed challenges and 
//    collect the points earned associated to such challenge
//
// 07/01/1    Kym Le              Original
// 09/22/13   Guna Sevugapperumal added public access modifier to SaveResult Inner class
// 10/18/13   Kym Le              Changed Points Buckets logic to use Challenge_Points_Bucket in save method
// 03/01/14   Kym Le              Changed awarding call to use GameEngine.AwardChallenge
// 07/28/14   Kym Le              Added CreatedById for SOQL query to retrieve points bucket to validate
// 09/17/15   Josh Tuttle         Added code for enforcing challenge limits (yearly, monthly, etc)


  public String selectedEmployee {get; set;}

    
  public ChallengeManagerController() { 
    //selectedDate = Date.Today().format();
    
    // URL parameter may specify a particular user for the "Appirian:" picklist
    selectedEmployee = ApexPages.CurrentPage().getParameters().get('userId');
  
    // otherwise, picklist should default to the current user
    if (selectedEmployee == null) selectedEmployee = UserInfo.getUserId();  
      
  }   
  
  @RemoteAction
  public static List<String> getDurationTypes() { 
    List<String> durations = new List<String>(); 
    
    Schema.DescribeFieldResult fieldResult =
      Challenge__c.Duration__c.getDescribe();
    List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
    
    for(Schema.PicklistEntry pl : ple){
      durations.add(pl.getValue());
    }   
    return durations;
  }
  
  @RemoteAction
  public static List<String> getCoreValueTypes() { 
    List<String> coreValues = new List<String>(); 
    
    Schema.DescribeFieldResult fieldResult =
      Challenge__c.Core_Value__c.getDescribe();
    List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
    
    for(Schema.PicklistEntry pl : ple){
      coreValues.add(pl.getValue());
    }   
    return coreValues;
  }
  
  @RemoteAction
  public static List<String> getFocusTypes() {
    List<String> focuses = new List<String>(); 
    
    Schema.DescribeFieldResult fieldResult =
      Challenge__c.Focus__c.getDescribe();
      List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
    
    for(Schema.PicklistEntry pl : ple){
      focuses.add(pl.getValue());
    }   
    return focuses;
  }
  
  @RemoteAction
  public static List<UserChallengeCounter> getAJChallengeMap(String selectedEmployee) {
    Map<String, UserChallengeCounter> challengeMap = new Map<String, UserChallengeCounter>();
    
    List<Challenge__c> cList = [SELECT   Name, 
                                         Title__c,
                                         Reward_Points__c,
                                         Max_Number_of_Achievements_Per_User__c,
                                         Duration__c,
                                         Automated__c,
                                         Hashtag__c,
                                         Start_Date__c,
                                         End_Date__c,
                                         Focus__c,
                                         Core_Value__c,
                                         Description__c,
                                         Active__c,
                                         Recently_Ended__c,
                                         Archived__c,
                                         Ended_in_Last_Year__c
                                FROM     Challenge__c
                                ORDER BY Title__c];
              
    for (Challenge__c challenge : cList) {
      challengeMap.put(challenge.id, new UserChallengeCounter(challenge));
    }
  
    List<Points__c> pList = [SELECT Id,
                                    Name,
                                    Challenge__r.Id,
                                    Amount__c,
                                    Date__c,
                                    Source__c,
                                    RecordType.Name
                             FROM   Points__c
                             WHERE  User__r.Id = :selectedEmployee
                             AND    Challenge__r.id != null
                             ORDER BY Challenge__r.Title__c];
  
    for (Points__c point : pList) {
      challengeMap.get(point.Challenge__r.id).inspectChallenge(point.Date__c);
    }
    return challengeMap.values();
  
  }
  
  public class SaveResult{
  
    public Boolean success;
    public String message;
    public Boolean maxNumberReached;
  
  }
  
  
  @RemoteAction
  public static SaveResult savePoints(String selectedUserId, String selectedChallengeId, String selectedDate, Integer currentAchievementCount) {
        
    Challenge__c c = [SELECT Id,
                             Name,
                             Title__c,
                             Reward_Points__c,
                             Active__c,
                             Max_Number_of_Achievements_Per_User__c,
                             Duration__c
                      FROM   Challenge__c
                      WHERE  Id = :selectedChallengeId];

    User u = [SELECT Id, Name FROM User WHERE Id = :UserInfo.getUserId()];                  
                      
    System.debug('Challenges: ' + c);                      
                      
    String notes = 'For completing challenge ' + c.Title__c;                  
    
    Date effectiveDate;
    
    if (selectedDate == '') {
      effectiveDate = Date.Today(); 
    } else {
      effectiveDate = Date.parse(selectedDate); 
    }
    
    List<Points__c> pList = [SELECT Id,
                                    Name,
                                    Challenge__r.Id,
                                    Amount__c,
                                    Date__c,
                                    Source__c,
                                    RecordType.Name
                             FROM   Points__c
                             WHERE  User__r.Id = :selectedUserId
                             AND    Challenge__r.id = :selectedChallengeId
                             ORDER BY Challenge__r.Title__c];
  
    for (Points__c point : pList) {
      System.debug('Point: ' + point);             
      Date pastEffectiveDate = point.Date__c;
      Integer daysPast = pastEffectiveDate.daysBetween(effectiveDate);
      
      if(c.Duration__c == 'monthly' && daysPast < 30){
      	SaveResult srFailedByDuration = new SaveResult();
        srFailedByDuration.success = false;
        srFailedByDuration.message= 'FAIL! You cannot complete the same challenge in last 30 days';
        
        return srFailedByDuration;
      }
      if(c.Duration__c == 'quarterly' && daysPast < 90){
      	SaveResult srFailedByDuration = new SaveResult();
        srFailedByDuration.success = false;
        srFailedByDuration.message= 'FAIL! You cannot complete the same challenge in last 90 days';
        
        return srFailedByDuration;
      }
      if(c.Duration__c == 'yearly' && daysPast < 365){
      	SaveResult srFailedByDuration = new SaveResult();
        srFailedByDuration.success = false;
        srFailedByDuration.message= 'FAIL! You cannot complete the same challenge in last 365 days';
        
        return srFailedByDuration;
      }
    }
                        
    List<Challenge_Points_Bucket__c> challengePointsBuckets = [SELECT Id, 
                                                   Points_Bucket__r.Id
                                            FROM   Challenge_Points_Bucket__c
                                            WHERE  Challenge__c = :c.Id
                                            AND    Points_Bucket__r.Owner__c = :UserInfo.getUserId() Limit 1]; 
        
    List<Points_Bucket__c> pointsBuckets = new List<Points_Bucket__c>();
    
    if (challengePointsBuckets.size() > 0) {                                        
      pointsBuckets = [SELECT Id, Current_Balance__c, Owner__c, CreatedById FROM Points_Bucket__c WHERE Id = :challengePointsBuckets[0].Points_Bucket__r.Id];                                            
    }
                                            
    PointsValidationResult pointsValidationResult = PointsValidator.validatePointsForAwardedChallenge(c, u, pointsBuckets);
    GameEngine.AwardedChallenge challengeToAward = new GameEngine.AwardedChallenge(c.Name, selectedUserId, UserInfo.getUserId(), effectiveDate, notes);
    
    
    SaveResult sr = new SaveResult();
       

       if (pointsValidationResult.isValid) {
          GameEngine.awardChallenge(challengeToAward);
        
        
          sr.success = true;
          currentAchievementCount++;
                                
          if (currentAchievementCount >= c.Max_Number_of_Achievements_Per_User__c) {
            sr.maxNumberReached = true;
          }   
       } else {                            
                                

        sr.success = false;
        sr.message= 'FAIL! ' + pointsValidationResult.errorMessage;
       }
     
    return sr;
  }
  
  @RemoteAction
  public static String getNewChallengeURL(){
    String newChallengeURL = '';
    
    Schema.DescribeSObjectResult r = Challenge__c.sObjectType.getDescribe();
    System.debug(r);
    
    if (r != null){
      newChallengeURL = '/' + r.getKeyPrefix() + '/o';
    }
    
    return newChallengeURL;
    
  }
  
  
}