src/objects/Challenge__c.object
<CustomObject>
    <description>Challenge in Game Engine</description>
    <fields>
        <fullName>Reward_Points__c</fullName>
        <description>Points awarded to the user upon completion of the Challenge</description>
        <inlineHelpText>Points awarded to the user upon completion of the Challenge</inlineHelpText>
        <label>Reward Points</label>
        <precision>5</precision>
        <scale>0</scale>
        
        <type>Number</type>
    </fields>
    <label>Challenge</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Name</label>
        
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Challenges</pluralLabel>
    <recordTypes>
        <fullName>Challenge</fullName>
        <active>true</active>
        <description>Base Challenge</description>
        <label>Challenge</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Challenge_Points_Bucket__c.object
<CustomObject>
    <description>Junction object, representing the M:N relationship between Challenges and Points Buckets.</description>
    <fields>
        <fullName>Challenge__c</fullName>
        <label>Challenge</label>
        <referenceTo>Challenge__c</referenceTo>
        <relationshipLabel>Points Buckets</relationshipLabel>
        <relationshipName>Challenge_Points_Buckets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Points_Bucket__c</fullName>
        <label>Points Bucket</label>
        <referenceTo>Points_Bucket__c</referenceTo>
        <relationshipLabel>Challenges</relationshipLabel>
        <relationshipName>Challenge_Points_Buckets</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Challenge Points Bucket</label>
    <nameField>
        <displayFormat>CPB-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Challenge Points Buckets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Points_Bucket__c.object
<CustomObject>
    <description>Funding source of a Challenge</description>
    <fields>
        <fullName>Current_Balance__c</fullName>
        <description>Current balance of the Points Bucket</description>
        <inlineHelpText>Current balance of the Points Bucket</inlineHelpText>
        <label>Current Balance</label>
        <precision>18</precision>
        <scale>0</scale>
        
        <type>Number</type>
    </fields>
    <label>Points Bucket</label>
    <nameField>
        <displayFormat>PB-{0000}</displayFormat>
        <label>Name</label>
        
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Points Buckets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ChallengePointsBucketHolder.cls
public with sharing class ChallengePointsBucketHolder {

  public Challenge__c challenge;
  private List<Challenge_Points_Bucket__c> cpb = new List<Challenge_Points_Bucket__c>();
  

  public ChallengePointsBucketHolder (Challenge__c ch) {
    challenge = ch;
  }
  
  public void addChallengePointsBucket(Challenge_Points_Bucket__c challengePB) {
    cpb.add(challengePB);
  }

  public Boolean deactivateChallenge() {
    
    for (Challenge_Points_Bucket__c c : cpb) {
      System.debug('FROM CPBH C: ' + c);
      System.debug('FROM CPBH CHALLENGE: ' + challenge);      
    
      if (c.Points_Bucket__r.Current_Balance__c >= challenge.Reward_Points__c) {
        return false;
      }
    }
    return true;
  }


}