src/objects/Challenge__c.object
<CustomObject>
    <description>Challenge in Game Engine</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Status of Challenge.</description>
        <inlineHelpText>Status of Challenge.</inlineHelpText>
        <label>Active</label>
        
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reward_Points__c</fullName>
        <description>Points awarded to the user upon completion of the Challenge</description>
        <inlineHelpText>Points awarded to the user upon completion of the Challenge</inlineHelpText>
        <label>Reward Points</label>
        <precision>5</precision>
        <scale>0</scale>
        
        <type>Number</type>
    </fields>
    <label>Challenge</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Name</label>
        
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Challenges</pluralLabel>
    <recordTypes>
        <fullName>Challenge</fullName>
        <active>true</active>
        <description>Base Challenge</description>
        <label>Challenge</label>
    </recordTypes>
    <recordTypes>
        <fullName>Chatter</fullName>
        <active>true</active>
        <description>Chatter Challenge</description>
        <label>Chatter</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Challenge_Points_Bucket__c.object
<CustomObject>
    <description>Junction object, representing the M:N relationship between Challenges and Points Buckets.</description>
    <fields>
        <fullName>Challenge__c</fullName>
        <label>Challenge</label>
        <referenceTo>Challenge__c</referenceTo>
        <relationshipLabel>Points Buckets</relationshipLabel>
        <relationshipName>Challenge_Points_Buckets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Points_Bucket__c</fullName>
        <label>Points Bucket</label>
        <referenceTo>Points_Bucket__c</referenceTo>
        <relationshipLabel>Challenges</relationshipLabel>
        <relationshipName>Challenge_Points_Buckets</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Challenge Points Bucket</label>
    <nameField>
        <displayFormat>CPB-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Challenge Points Buckets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Points__c.object
<CustomObject>
    <description>Earned or spent Points per user.</description>
    <fields>
        <fullName>Challenge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Challenge that the user has completed to earn points</description>
        <inlineHelpText>Challenge that the user has completed to earn points</inlineHelpText>
        <label>Challenge</label>
        <referenceTo>Challenge__c</referenceTo>
        <relationshipLabel>Points</relationshipLabel>
        <relationshipName>Earned_Points</relationshipName>
        
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Points_Bucket__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Points Bucket</label>
        <referenceTo>Points_Bucket__c</referenceTo>
        <relationshipLabel>Points</relationshipLabel>
        <relationshipName>Points</relationshipName>
        
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Target_Record_Id__c</fullName>
        <description>For Earned Points: the Id of the Object that references the Points that were awarded.

For Transferred Points: the Id of the Object to WHERE the points were transferred to.</description>
        <inlineHelpText>For Earned Points: the Id of the Object that references the Points that were awarded.

For Transferred Points: the Id of the Object to WHERE the points were transferred to.</inlineHelpText>
        <label>Target Record Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>User that has earned the Challenge points</description>
        <inlineHelpText>User that has earned the Challenge points</inlineHelpText>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Earned_Points</relationshipName>
        
        <type>Lookup</type>
    </fields>
    <label>Points</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Name</label>
        
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Points</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Points_Bucket__c.object
<CustomObject>
    <description>Funding source of a Challenge</description>
    <fields>
        <fullName>Current_Balance__c</fullName>
        <description>Current balance of the Points Bucket</description>
        <inlineHelpText>Current balance of the Points Bucket</inlineHelpText>
        <label>Current Balance</label>
        <precision>18</precision>
        <scale>0</scale>
        
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Owner of the Points Bucket</description>
        <inlineHelpText>Owner of the Points Bucket</inlineHelpText>
        <label>Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Points_Buckets</relationshipName>
        
        <type>Lookup</type>
    </fields>
    <label>Points Bucket</label>
    <nameField>
        <displayFormat>PB-{0000}</displayFormat>
        <label>Name</label>
        
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Points Buckets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PointsValidator.cls
public class PointsValidator {

//
// (c) Appirio 2014
//
// Points Validator class.  Returns a Points Validation Result.
//
// 1.  Validate Points based on Challenge being active.
//
// 2.  Validate Points based on Points Bucket having enough points for the Awarding From User or 
//     by the no owner Points Bucket.
//
// 3.  Helper method to return Points Buckets for a list of Challenge Ids.
// 
// 4.  Helper method that determins if user has already been awarded based on a Target Object Id.
//
// 5.  Helper method that gets all users who have been awarded Points that have a Target Object Id.
//
// 
// 03/01/2014     Kym Le    Original
// 03/04/2014     Kym Le    Added code to handle error case when user does not send in an @mentions 
//                          to a chatter challenge
// 07/20/2014     Kym Le    Added logic to account for Shareable Points Bucket - points should be taken
//                          from user's Shareable Points Bucket first, then Manager's Points Bucket, and then, lastly,
//                          a Points Bucket that has no owner



  public static PointsValidationResult validatePointsForAwardedChallenge(Challenge__c challenge, User user, List<Points_Bucket__c> pointsBucketList){
    return validatePointsForAwardedChallenge(1, challenge, user, pointsBucketList);
  }
  
  
  public static PointsValidationResult validatePointsForAwardedChallenge(Integer totalTimesChallengeAwarded, Challenge__c challenge, User user, List<Points_Bucket__c> availablePb){
  
    PointsValidationResult result = new PointsValidationResult();
    result.isValid = true;
    result.pointsBucketToUse = null;
    Double rewardPoints = challenge.Reward_Points__c * totalTimesChallengeAwarded;
    
    if (!challenge.Active__c) {
      result.isValid = false;
      result.errorMessage = 'You can not award an inactive Challenge';
      
      return result;
    }
    
    if (totalTimesChallengeAwarded == 0) {
      result.isValid = false;
      result.errorMessage = 'Challenge needs to be awarded to at least 1 user';
    }
    
    if(availablePb == null){
      return result;
    }
    
    //if the Awarded From User is not specified, set it to the logged in User
    if (user == null) {
      user = [SELECT Id, 
                     Name 
              FROM   User 
              WHERE  Id = :UserInfo.getUserId()];
    }
    
    //point bucket that has createdby and owner as the same Id
    Points_Bucket__c ownerShareablePointBucket = null;
    
    Points_Bucket__c ownerPointBucket = null;
    Points_Bucket__c noOwnerPointBucket = null;
            
    //find out if there's a point bucket owned by the awarding user
    for(Points_Bucket__c pb : availablePb) {
      if(pb.Owner__c == user.Id && pb.CreatedById == user.Id) {
        ownerShareablePointBucket = pb;
      }  
      else if(pb.Owner__c == user.Id && pb.CreatedById != user.Id) {
        ownerPointBucket = pb;
      }
    }         

    //find out if there's a point bucket with no owner
    for(Points_Bucket__c pb : availablePb) {
      if(pb.Owner__c == null){
        noOwnerPointBucket = pb;
        break;
      }
    }
    
    //figure out which Points Bucket to use
    if (ownerShareablePointBucket != null && ownerShareablePointBucket.Current_Balance__c >= rewardPoints) {
      result.pointsBucketToUse = ownerShareablePointBucket;
    } else if (ownerPointBucket != null && ownerPointBucket.Current_Balance__c >= rewardPoints) {
      result.pointsBucketToUse = ownerPointBucket;
    } else {
      result.pointsBucketToUse = noOwnerPointBucket;
    }
      
      
    //if the owners Shareable Points Bucket does not have enough points and there is no other Points Bucket
    if (ownerShareablePointBucket != null && ownerPointBucket == null && noOwnerPointBucket == null && ownerShareablePointBucket.Current_Balance__c < rewardPoints) {
      System.debug('Adding to Exception list');
      result.isValid = false;
      result.errorMessage = 'There is no available Points Bucket with sufficient points for ' + user.Name + ' to award this challenge.';
    }
    
    //if the owners Shareable Points Bucket and Manager Points Bucket do not have enough points and there is no open Points Bucket
    if (ownerShareablePointBucket != null && ownerPointBucket != null && noOwnerPointBucket == null && ownerShareablePointBucket.Current_Balance__c < rewardPoints && ownerPointBucket.Current_Balance__c < rewardPoints) {
      System.debug('Adding to Exception list');
      result.isValid = false;
      result.errorMessage = 'There is no available Points Bucket with sufficient points for ' + user.Name + ' to award this challenge.';
    }
        
    //no Points Bucket for the user, there's an open Points Bucket but not enough points in there
    if (ownerShareablePointBucket == null && ownerPointBucket == null && noOwnerPointBucket != null && noOwnerPointBucket.Current_Balance__c < rewardPoints){
      System.debug('Adding to Exception list');
      result.isValid = false;
      result.errorMessage = 'There is no available Points Bucket with sufficient points for ' + user.Name + ' to award this challenge.';
    }

    //no Points Bucket for the user
    if (ownerShareablePointBucket == null && ownerPointBucket == null && noOwnerPointBucket == null && !availablePb.isEmpty()){
      System.debug('Adding to Exception list - Here!');
      result.isValid = false;
      result.errorMessage = 'There is no available Points Bucket for ' + user.Name + ' to award this challenge.';
    }   
        
    return result;     
  }
  
  
  public static Map<Id, List<Points_Bucket__c>> getPointsBucketsForChallenges(Set<Id> challengeIds) {
    //map of Challenge Id and list of Points Bucket                                        
    Map<Id, List<Points_Bucket__c>> challengeIdAndPointsBucketMap = new Map<Id, List<Points_Bucket__c>>();  

    //list of all the Points Buckets Ids that are possible for the Challenges coming in from the trigger                                                        
    List<Id> pointsBucketIds = new List<Id>();


    //list of all the challenge points buckets by challenge from the trigger                                                    
    List<Challenge_Points_Bucket__c> avaliableChallengePointsBuckets = [SELECT Id, 
                                                                               Challenge__c, 
                                                                               Points_Bucket__c 
                                                                        FROM   Challenge_Points_Bucket__c 
                                                                        WHERE  Challenge__c in :challengeIds];  
                                                                          
    if (avaliableChallengePointsBuckets.size() == 0) {
      return challengeIdAndPointsBucketMap;
    }                                                                          

    //populate the list with the Ids of the possible Points Buckets for the Challenges
    for (Challenge_Points_Bucket__c challengePointsBucket : avaliableChallengePointsBuckets) {
      pointsBucketIds.add(challengePointsBucket.Points_Bucket__c);
    }                                                                                                                                                                        
    
    //get all the Points Buckets that are possible
    Map<Id, Points_Bucket__c> pointsBucketMap = new Map<Id, Points_Bucket__c>([SELECT Id, 
                                                                                      Current_Balance__c, 
                                                                                      Owner__c,
                                                                                      CreatedById
                                                                               FROM   Points_Bucket__c 
                                                                               WHERE  Id in :pointsBucketIds]);                                          
                                       
    //loop through the possible Challenge Points Bucket and populate the list and map needed later
    for (Challenge_Points_Bucket__c cpb : avaliableChallengePointsBuckets) {

      List<Points_Bucket__c> pB = challengeIdAndPointsBucketMap.get(cpb.Challenge__c);
      
      if (pB == null) {
        pB = new List<Points_Bucket__c>();
      }
      
      pB.add(pointsBucketMap.get(cpb.Points_Bucket__c));
      challengeIdAndPointsBucketMap.put(cpb.Challenge__c, pB);
    }

    return challengeIdAndPointsBucketMap; 
  }
  
  
  public static Map<Id, List<Points__c>> getAllUsersAndPointsForTargetRecordId(Set<Id> userIds) {
  
    Map<Id, List<Points__c>> userIdAndPointsMap = new Map<Id, List<Points__c>>();
    
    //get the list of all points for all the users that have a target record id
    List<Points__c> userPoints = new List<Points__c>([SELECT Id, 
                                                             User__c, 
                                                             Target_Record_Id__c 
                                                      FROM   Points__c 
                                                      WHERE  User__c in :userIds
                                                      AND    Target_Record_Id__c != '']);                        
                        
    for (Points__c point : userPoints) {
      List<Points__c> pointsList = userIdAndPointsMap.get(point.User__c);
      
      if (pointsList == null) {
        pointsList = new List<Points__c>();
        
      }
      
      pointsList.add(point);    
      userIdAndPointsMap.put(point.User__c, pointsList);
    }  
    
    return userIdAndPointsMap;      
  }
  
  
  public static Boolean userHasAlreadyBeenAwardedTargetId(List<Points__c> userPoints, String targetRecordId) {
  
    if (userPoints != null) {
      for (Points__c point : userPoints) {
        System.debug('point: ' + point.Target_Record_Id__c);
        if (point.Target_Record_Id__c == targetRecordId) {
          return true;
        }
      }  
    }
        
    return false;
  }
  
}