src/objects/Challenge__c.object
<CustomObject>
    <description>Challenge in Game Engine</description>
    <fields>
        <fullName>Max_Number_of_Achievements_Per_User__c</fullName>
        <description>Maximum number of times a particular user can achieve this Challenge.</description>
        <inlineHelpText>Maximum number of times a particular user can achieve this Challenge.</inlineHelpText>
        <label>Max Number of Achievements Per User</label>
        <precision>3</precision>
        <scale>0</scale>
        
        <type>Number</type>
    </fields>
    <label>Challenge</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Name</label>
        
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Challenges</pluralLabel>
    <recordTypes>
        <fullName>Challenge</fullName>
        <active>true</active>
        <description>Base Challenge</description>
        <label>Challenge</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/UserChallengeCounter.cls
public class UserChallengeCounter{

  public Challenge__c challenge { get; set; }
  public Integer count { get; set; }
  public Date lastAwardedDate { get; set; }
  public Boolean maxNumberReached { get; set; }

  public UserChallengeCounter(Challenge__c c){
    maxNumberReached = false;
    challenge = c;
    count = 0;
  }

  public void inspectChallenge(Date challengeDateAwarded){
  
    count++;
    if(lastAwardedDate == null){
      lastAwardedDate = challengeDateAwarded;
    }else if(challengeDateAwarded > lastAwardedDate){
      lastAwardedDate = challengeDateAwarded;
    }
    
    if(count >= challenge.Max_Number_of_Achievements_Per_User__c){
      maxNumberReached = true;
    }
  }
 
}