src/objects/Game_Security__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Security permissions for the Appirio Gamification Engine (AGE).</description>
    <fields>
        <fullName>Award_Badge_to_Another_User__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The current user can award badges to another user.</description>
        <inlineHelpText>The current user can award badges to another user.</inlineHelpText>
        <label>Award Badge to Another User</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Award_Points_to_Another_User__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The current user can award points to another user.</description>
        <inlineHelpText>The current user can award points to another user.</inlineHelpText>
        <label>Award Points to Another User</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Create_New_Badge__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Ability to create a new badge.</description>
        <inlineHelpText>Ability to create a new badge.</inlineHelpText>
        <label>Create New Badge</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Create_New_Challenge__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The user can create a new Challenge.</description>
        <inlineHelpText>The user can create a new Challenge.</inlineHelpText>
        <label>Create New Challenge</label>
        <type>Checkbox</type>
    </fields>
    <label>Game Security</label>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Full_Name__c</fullName>
        <description>First name plus last name.  Formula field.</description>
        <formula>FirstName &amp; &quot; &quot; &amp; LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>First name plus last name.  Formula field.</inlineHelpText>
        <label>Full Name</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/AgeUserController.cls
public virtual class AgeUserController {

  
  public AgeUserController(){
  
  }
  
  @RemoteAction
  public static User getLoggedInUser(){
  
    return [SELECT Name,
                   SmallPhotoUrl
            FROM   User
            WHERE  Id = :UserInfo.getUserId()];
  }


  @RemoteAction
  public static List<User> getAllUsers() {
    
    return [SELECT   Id, 
                     Name, 
                     FirstName,
                     Full_Name__c 
            FROM     User 
            WHERE    Usertype = 'Standard'
            AND      isActive = true
            ORDER BY Full_Name__c];
  }

  @RemoteAction
  public static Game_Security__c getUserSecuritySettings() {
  
    List<Game_Security__c> userSecurity =  [SELECT SetupOwnerId, 
                   Create_New_Challenge__c, 
                   Award_Points_to_Another_User__c,
                   Award_Badge_to_Another_User__c,                    
                   Create_New_Badge__c 
            FROM   Game_Security__c
            WHERE  SetupOwnerId = :UserInfo.getUserId() Limit 1]; 
    
    if (userSecurity.size() == 0) {
      return new Game_Security__c();
    }     
            
    return userSecurity[0];
  }
}