src/objects/Game_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>Settings for the Appirio Gamification Engine (AGE).</description>
    <fields>
        <fullName>Challenge_Idea_Gets_Implemented__c</fullName>
        <description>Automated awarding of Challenge - Idea Gets Implemented</description>
        <inlineHelpText>Automated awarding of Challenge - Idea Gets Implemented</inlineHelpText>
        <label>Challenge - Idea Gets Implemented</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Game Settings</label>
</CustomObject>

agesrc/objects/Points__c.object
<CustomObject>
    <description>Earned or spent Points per user.</description>
    <label>Points</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Points</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

agesrc/classes/IdeaTriggerHandler.cls
public with sharing class IdeaTriggerHandler {

  private boolean m_isExecuting = false;
  
  public IdeaTriggerHandler(boolean isExecuting){
    m_isExecuting = isExecuting;
  }

  
  public void OnAfterUpdate(Map<Id, Idea> newIdea){
  
    Set<Id> userIds = new Set<Id>();
    List<GameEngine.AwardedChallenge> awardedChallengesList = new List<GameEngine.AwardedChallenge>();
    Map<Id, List<Points__c>> userIdAndPointsMap = new Map<Id, List<Points__c>>();
  
    //get the challenge for Ideas get Implemented 
    String challenge = Game_Settings__c.getInstance().Challenge_Idea_Gets_Implemented__c;
    System.debug('Game Setting Challenge: ' + challenge);
  
    //if there's no challenge, exit out
    if(challenge == '') {
      return;
    }      
  
    //get all the ideas that have a status of implemented
    Map<Id, Idea> ideasToProcess = new Map<Id, Idea>([SELECT Id, 
                                                             Title,
                                                             CreatedById
                                                      FROM   Idea 
                                                      WHERE  Status = 'Implemented!'
                                                      AND    Id IN :newIdea.keySet()]);
                                                      
    System.debug('Ideas: ' + ideasToProcess);                                                      
                                       
    if (ideasToProcess.isEmpty() == false) {
      
      //get all the users that have implemented ideas
      for (Idea i : ideasToProcess.values()) {
        userIds.add(i.CreatedById);
      }
  
     
      userIdAndPointsMap = PointsValidator.getAllUsersAndPointsForTargetRecordId(userIds);
  
  
      for(Idea i : ideasToProcess.values()) {
        System.debug('process the idea');
    
        if (!PointsValidator.userHasAlreadyBeenAwardedTargetId(userIdAndPointsMap.get(i.CreatedById), i.Id)) {
                   
          GameEngine.AwardedChallenge awardedChallenge = new GameEngine.AwardedChallenge(challenge, i.createdById, Date.Today(), 'For idea that was implemented', i.Title, i.Id);
          awardedChallengesList.add(awardedChallenge);
          
          System.debug('awarded challenge: ' + awardedChallenge);
            
        }
      }
      
      
      System.debug('awarded challenge list: ' + awardedchallengesList);
      if (awardedChallengesList.size() > 0) {
      
        GameEngine.AwardChallenge(awardedChallengesList);
      }
    }
  }

}