agesrc/objects/Awarded_Badge__c.object
<CustomObject>
    <description>Represents the awarding of a particular Badge to a particular User.</description>
    <fields>
        <fullName>Badge_Title__c</fullName>
        <formula>Badge__r.Title__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Badge Title</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Badge__c</fullName>
        <label>Badge</label>
        <referenceTo>Badge__c</referenceTo>
        <relationshipLabel>Awarded To</relationshipLabel>
        <relationshipName>Awarded_Badges</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <description>Date in which the Awarded Badge is effective</description>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Awarded_Badges</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Awarded Badge</label>
    <nameField>
        <displayFormat>AB-{00000}</displayFormat>
        <label>Awarded Badge Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Awarded Badges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

agesrc/objects/Badge__c.object
<CustomObject>
    <description>Badges that are obtained by completed specified Challenge(s)</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Status of Badge.</description>
        <inlineHelpText>Status of Badge.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Core_Value__c</fullName>
        <description>Core Value associated to the Badge</description>
        <inlineHelpText>Core Value associated to the Badge</inlineHelpText>
        <label>Core Value</label>
        <picklist>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fun</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description of the Badge</description>
        <inlineHelpText>Description of the Badge</inlineHelpText>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Focus__c</fullName>
        <description>Focus associated to the Badge</description>
        <inlineHelpText>Focus associated to the Badge</inlineHelpText>
        <label>Focus</label>
        <picklist>
            <picklistValues>
                <fullName>[topcoder]</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anniversaries</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assets</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awards</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Continuing Ed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cornerstone OnDemand Certification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Google Certification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Certification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recognition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recruiting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Salesforce Certification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shoutouts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Silver Lining</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Strategy Certification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Workday Certification</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Image_URL__c</fullName>
        <description>URL for image associated to Badge</description>
        <inlineHelpText>URL for image associated to Badge</inlineHelpText>
        <label>Image URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>Title for the Badge</description>
        <inlineHelpText>Title for the Badge</inlineHelpText>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Badge</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Badges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Badge_Challenge__c.object
<CustomObject>
    <description>Ties Challenges to Badges.</description>
    <fields>
        <fullName>Badge_Title__c</fullName>
        <formula>Badge__r.Title__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Badge Title</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Badge__c</fullName>
        <label>Badge</label>
        <referenceTo>Badge__c</referenceTo>
        <relationshipLabel>Required Challenges</relationshipLabel>
        <relationshipName>Badge_Challenges</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Challenge_Title__c</fullName>
        <formula>Challenge__r.Title__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Challenge Title</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Challenge__c</fullName>
        <label>Challenge</label>
        <referenceTo>Challenge__c</referenceTo>
        <relationshipLabel>Included in Badges</relationshipLabel>
        <relationshipName>Badge_Challenges</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Tag_Match__c</fullName>
        <description>Optional - a comma-delimited list of &quot;Points.Tag&quot; values, each of which qualify the specified Challenge for this Badge.  For example, a certification-related Badge might require a particular certification challenge, not just &quot;any&quot; certification.</description>
        <inlineHelpText>Optional - a comma-delimited list of &quot;Points.Tag&quot; values, each of which qualify the specified Challenge for this Badge.  For example, a certification-related Badge might require a particular certification challenge, not just &quot;any&quot; certification.</inlineHelpText>
        <label>Tag Match</label>
        <length>32768</length>
        
        <type>LongTextArea</type>
    </fields>
    <label>Badge Challenge</label>
    <nameField>
        <displayFormat>BC-{0000}</displayFormat>
        <label>Name</label>
        
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Badge Challenges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Challenge__c.object
<CustomObject>
    <description>Challenge in Game Engine</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Status of Challenge.</description>
        <inlineHelpText>Status of Challenge.</inlineHelpText>
        <label>Active</label>
        
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Core_Value__c</fullName>
        <description>Core Value associated to the Challenge</description>
        <inlineHelpText>Core Value associated to the Challenge</inlineHelpText>
        <label>Core Value</label>
        <picklist>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fun</fullName>
            </picklistValues>
        </picklist>
        
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description of the Challenge</description>
        <inlineHelpText>Description of the Challenge</inlineHelpText>
        <label>Description</label>
        
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Focus__c</fullName>
        <description>Focus associated to Challenge</description>
        <inlineHelpText>Focus associated to Challenge</inlineHelpText>
        <label>Focus</label>
        <picklist>
            <picklistValues>
                <fullName>Anniversaries</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assets</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awards</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Continuing Ed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recognition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recruiting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shoutouts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Silver Lining</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Topcoder</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>Title for the Challenge</description>
        <inlineHelpText>Title for the Challenge</inlineHelpText>
        <label>Title</label>
        <length>255</length>
        
        <type>Text</type>
    </fields>
    <label>Challenge</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Name</label>
        
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Challenges</pluralLabel>
    <recordTypes>
        <fullName>Challenge</fullName>
        <active>true</active>
        <description>Base Challenge</description>
        <label>Challenge</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

agesrc/classes/BadgesController.cls
public class BadgesController extends AgeUserController{

//
// (c) Appirio 
//
// Appirio's Gamification App
//    This controller allows users to enter in their completed challenges and 
//    collect the points earned associated to such challenge
//
// 9/26/13     Kym Le     Original
// 9/30/2013   Guna Sevugapperumal  added 2 methods to BatchHolder inner
//                                  class for covering unit test
//

  public String selectedEmployee {get; set;}

  public BadgesController(){
  
    // URL parameter may specify a particular user for the "Appirian:" picklist
    selectedEmployee = ApexPages.CurrentPage().getParameters().get('userId');
  
    // otherwise, picklist should default to the current user
    if (selectedEmployee == null) selectedEmployee = UserInfo.getUserId();  
  
  }
  
  @RemoteAction
  public static List<String> getCoreValueTypes() { 
    List<String> coreValues = new List<String>(); 
    
    Schema.DescribeFieldResult fieldResult =
      Challenge__c.Core_Value__c.getDescribe();
    List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
    
    for(Schema.PicklistEntry pl : ple){
      coreValues.add(pl.getValue());
    }   
    return coreValues;
  }

  @RemoteAction
  public static List<String> getFocusTypes() {
    List<String> focuses = new List<String>(); 
    
    Schema.DescribeFieldResult fieldResult =
      Challenge__c.Focus__c.getDescribe();
      List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
    
    for(Schema.PicklistEntry pl : ple){
      focuses.add(pl.getValue());
    }   
    
    return focuses;
  }
  
  
  @RemoteAction
  public static List<BadgeHolder> getAllBadges(String selectedEmployee) {
  
    List<Badge__c> allBadges = [SELECT Id, 
                                       Title__c, 
                                       Image_Url__c,
                                       Focus__c, 
                                       Core_Value__c, 
                                       Active__c,
                                       Description__c,
                                       (SELECT Id, 
                                               CreatedDate 
                                        FROM   Awarded_Badges__r 
                                        WHERE  User__c = :selectedEmployee
                                        ORDER By CreatedDate Desc
                                        LIMIT 1) 
                                FROM   Badge__c];
                              
    List<Badge_Challenge__c> allBadgeChallenges = [SELECT Badge__c, 
                                                          Badge_Title__c, 
                                                          Challenge__c, 
                                                          Challenge_Title__c, 
                                                          Tag_Match__c 
                                                   FROM   Badge_Challenge__c];
    
    
    Map<Id, BadgeHolder> badgeHolderMap = new Map<Id, BadgeHolder>();
    
    for(Badge__c b : allBadges) {
      badgeHolderMap.put(b.Id, new BadgeHolder(b));
    
    }                           
    
    for (Badge_Challenge__c bc : allBadgeChallenges) {
      badgeHolderMap.get(bc.badge__c).addBadgeChallenge(bc);
    
    }
                              
    return badgeHolderMap.values();                          
  }
  
  
  @RemoteAction
  public static SaveResult saveAwardedBadge(String selectedUserId, String selectedBadgeId, String selectedDate) {
    Awarded_Badge__c ab = new Awarded_Badge__c();
        
    ab.User__c = selectedUserId;
    ab.Badge__c = selectedBadgeId;
    
    if (selectedDate == '') {
      ab.Effective_Date__c = Date.Today(); 
    } else {
      ab.Effective_Date__c = date.parse(selectedDate); 
    }
    
    SaveResult sr = new SaveResult();
       
    try {
        insert ab;
        sr.success = true;
                                                      
    } catch (Exception e) {
        sr.success = false;
        sr.message= 'FAIL!' + e.getMessage();
    } 
     
    return sr;
  }
  
  public class SaveResult{
  
    public Boolean success;
    public String message;
  
  }
  
  @RemoteAction
  public static String getNewBadgeURL(){
    String newBadgeURL = '';
    
    Schema.DescribeSObjectResult r = Badge__c.sObjectType.getDescribe();
    System.debug(r);
    
    if (r != null){
      newBadgeURL = '/' + r.getKeyPrefix() + '/o';
    }
    
    return newBadgeURL;
    
  }
  
  public class BadgeHolder{
    private Badge__c badge{get;set;}
    private List<Badge_Challenge__c> badgeChallenges{get;set;}
  
    public BadgeHolder(Badge__c b) {
      badge = b;
      badgeChallenges = new List<Badge_Challenge__c>();
    }
    
    
    public void addBadgeChallenge(Badge_Challenge__c bc) {
      badgeChallenges.add(bc);
    }
    // Guna added this to cover the test cases Sep 30 2013
    public Badge__c getThisBadge(){
        return badge;
    }
   
    // Guna added this to cover the test cases Sep 30 2013 
    public List<Badge_Challenge__c> getThisChallenges(){
        return badgeChallenges;
    }
    
  }
}