agesrc/objects/Awarded_Badge__c.object
<CustomObject>
    <description>Represents the awarding of a particular Badge to a particular User.</description>
    <fields>
        <fullName>Badge__c</fullName>
        <label>Badge</label>
        <referenceTo>Badge__c</referenceTo>
        <relationshipLabel>Awarded To</relationshipLabel>
        <relationshipName>Awarded_Badges</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Awarded_Badges</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Awarded Badge</label>
    <nameField>
        <displayFormat>AB-{00000}</displayFormat>
        <label>Awarded Badge Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Awarded Badges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

agesrc/objects/Badge__c.object
<CustomObject>
    <description>Badges that are obtained by completed specified Challenge(s)</description>
    <fields>
        <fullName>Title__c</fullName>
        <description>Title for the Badge</description>
        <inlineHelpText>Title for the Badge</inlineHelpText>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Badge</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Badges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Challenge__c.object
<CustomObject>
    <description>Challenge in Game Engine</description>
    <fields>
        <fullName>Title__c</fullName>
        <description>Title for the Challenge</description>
        <inlineHelpText>Title for the Challenge</inlineHelpText>
        <label>Title</label>
        <length>255</length>
        
        <type>Text</type>
    </fields>
    <label>Challenge</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Name</label>
        
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Challenges</pluralLabel>
    <recordTypes>
        <fullName>Challenge</fullName>
        <active>true</active>
        <description>Base Challenge</description>
        <label>Challenge</label>
    </recordTypes>
    <recordTypes>
        <fullName>Chatter</fullName>
        <active>true</active>
        <description>Chatter Challenge</description>
        <label>Chatter</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Challenge_Points_Bucket__c.object
<CustomObject>
    <description>Junction object, representing the M:N relationship between Challenges and Points Buckets.</description>
    <fields>
        <fullName>Challenge__c</fullName>
        <label>Challenge</label>
        <referenceTo>Challenge__c</referenceTo>
        <relationshipLabel>Points Buckets</relationshipLabel>
        <relationshipName>Challenge_Points_Buckets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Points_Bucket__c</fullName>
        <label>Points Bucket</label>
        <referenceTo>Points_Bucket__c</referenceTo>
        <relationshipLabel>Challenges</relationshipLabel>
        <relationshipName>Challenge_Points_Buckets</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Challenge Points Bucket</label>
    <nameField>
        <displayFormat>CPB-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Challenge Points Buckets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Game_Security__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Security permissions for the Appirio Gamification Engine (AGE).</description>
    <fields>
        <fullName>Remove_Points__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The ability to remove Points from another user.  (Any user can remove their own points.)</description>
        <inlineHelpText>The ability to remove Points from another user.  (Any user can remove their own points.)</inlineHelpText>
        <label>Remove Points</label>
        <type>Checkbox</type>
    </fields>
    <label>Game Security</label>
</CustomObject>

src/objects/Game_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>Settings for the Appirio Gamification Engine (AGE).</description>
    <fields>
        <fullName>Chatter_Challenges_For_Points_Bucket__c</fullName>
        <description>Challenges associated to the shareable Points Bucket a user creates from the Point Summary page.</description>
        <inlineHelpText>Challenges associated to the shareable Points Bucket a user creates from the Point Summary page.</inlineHelpText>
        <label>Chatter Challenges For Points Bucket</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_Store_TargetRecordId__c</fullName>
        <description>The Id for the Company Store.  This is an arbitrary Id.</description>
        <inlineHelpText>The Id for the Company Store.  This is an arbitrary Id.</inlineHelpText>
        <label>Company Store TargetRecordId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Earned_Points_RecordTypeId__c</fullName>
        <description>The Id for the Record Type of Earned Points.</description>
        <inlineHelpText>The Id for the Record Type of Earned Points.</inlineHelpText>
        <label>Earned Points RecordTypeId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transferred_Points_RecordTypeId__c</fullName>
        <description>The Id of the Record Type for Transferred Points.</description>
        <inlineHelpText>The Id of the Record Type for Transferred Points.</inlineHelpText>
        <label>Transferred Points RecordTypeId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Game Settings</label>
</CustomObject>

agesrc/objects/Log_Message__c.object
<CustomObject>
    <description>A custom log message, typically written by an Appirio-authored process, e.g. a trigger or scheduled Apex.  Admins may wish to create workflow alerts to be notified about certain types of log messages.</description>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>New Public Report Folder</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Log Message</label>
    <nameField>
        <displayFormat>LM-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Log Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

agesrc/objects/Points__c.object
<CustomObject>
    <description>Earned or spent Points per user.</description>
    <fields>
        <fullName>Amount__c</fullName>
        <description>Amount of Points</description>
        <inlineHelpText>Amount of Points</inlineHelpText>
        <label>Amount</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Challenge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Challenge that the user has completed to earn points</description>
        <inlineHelpText>Challenge that the user has completed to earn points</inlineHelpText>
        <label>Challenge</label>
        <referenceTo>Challenge__c</referenceTo>
        <relationshipLabel>Points</relationshipLabel>
        <relationshipName>Earned_Points</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>today()</defaultValue>
        <description>Effective date, i.e. the date the points were actually earned.</description>
        <inlineHelpText>Effective date, i.e. the date the points were actually earned.</inlineHelpText>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Entered_in_Company_Store__c</fullName>
        <defaultValue>false</defaultValue>
        <description>IT will check this box when these points have been added to the user&apos;s Company Store balance.</description>
        <inlineHelpText>IT will check this box when these points have been added to the user&apos;s Company Store balance.</inlineHelpText>
        <label>Entered in Company Store</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <description>Notes on how or why these points were assigned.</description>
        <inlineHelpText>Notes on how or why these points were assigned.</inlineHelpText>
        <label>Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Points_Bucket__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Points Bucket</label>
        <referenceTo>Points_Bucket__c</referenceTo>
        <relationshipLabel>Points</relationshipLabel>
        <relationshipName>Points</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <description>Where the points are coming from.</description>
        <inlineHelpText>Where the points are coming from.</inlineHelpText>
        <label>Source</label>
        <picklist>
            <picklistValues>
                <fullName>Challenge Completed</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Manager Bucket</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Points Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Transaction status of the points.</description>
        <inlineHelpText>Transaction status of the points.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Tag__c</fullName>
        <description>Optional tag representing an attribute of the award.  For example, when a user achieves a professional certification, they may be awarded the &quot;Certification&quot; challenge, with the Tag set to the name of the certification.</description>
        <inlineHelpText>Optional tag representing an attribute of the award.  For example, when a user achieves a professional certification, they may be awarded the &quot;Certification&quot; challenge, with the Tag set to the name of the certification.</inlineHelpText>
        <label>Tag</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Target_Record_Id__c</fullName>
        <description>For Earned Points: the Id of the Object that references the Points that were awarded.

For Transferred Points: the Id of the Object to WHERE the points were transferred to.</description>
        <inlineHelpText>For Earned Points: the Id of the Object that references the Points that were awarded.

For Transferred Points: the Id of the Object to WHERE the points were transferred to.</inlineHelpText>
        <label>Target Record Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>The Type of points</description>
        <inlineHelpText>The Type of points</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>General</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shareable</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>User that has earned the Challenge points</description>
        <inlineHelpText>User that has earned the Challenge points</inlineHelpText>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Earned_Points</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Points</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Points</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

agesrc/objects/Points_Bucket__c.object
<CustomObject>
    <description>Funding source of a Challenge</description>
    <fields>
        <fullName>Current_Balance__c</fullName>
        <description>Current balance of the Points Bucket</description>
        <inlineHelpText>Current balance of the Points Bucket</inlineHelpText>
        <label>Current Balance</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Owner of the Points Bucket</description>
        <inlineHelpText>Owner of the Points Bucket</inlineHelpText>
        <label>Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Points_Buckets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Points Bucket</label>
    <nameField>
        <displayFormat>PB-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Points Buckets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

agesrc/objects/User.object
<CustomObject>
    <fields>
        <fullName>Direct_Deposit_Points_Into_Company_Store__c</fullName>
        <defaultValue>true</defaultValue>
        <description>AGE setting that indicates automatic transfer of all available points to the Company Store.</description>
        <inlineHelpText>AGE setting that indicates automatic transfer of all available points to the Company Store.</inlineHelpText>
        <label>Direct Deposit Points Into Company Store</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

agesrc/classes/PointsSummaryController.cls
public class PointsSummaryController {

//
// (c) Appirio
//
// 2013-07-11     Glenn Weinstein     Original
// 2013-10-02     Glenn Weinstein     Can only remove other users' points if you have that security permission
// 2013-10-13     Guna                Made thisQuarter() method public
// 2013-10-18     Glenn Weinstein     Add Badge Summary
// 2013-10-24     Glenn Weinstein     Add "Entered in Company Store" field on Points
// 2014-07-20     Kym Le                  Added changes for transferring points



  public Points__c proxyPoints {get; set;}   // a temporary "Points" object used solely for its User__c field, which we'll
                                             // bind to the "Appirian" lookup on the page (i.e. the selected user)
  
  public List<Points__c> points;
  public List<Awarded_Badge__c> badges;

  public String selectedPointsId {get; set;}
  public String selectedBadgeId {get; set;}
  public Boolean canRemovePoints {get; set;}

  public Decimal pointsEarnedTotal {get; set;}
  public Decimal pointsTransferredToCompanyStoreTotal {get; set;}
  public Decimal pointsTransferredToPointsBucketsTotal {get; set;}
  public Decimal pointsEarnedThisQuarter {get; set;}
  public Boolean showNewPointsBucketName {get; set;}
  public Decimal pointsBalance {get; set;}
  public Decimal transferAmount {get; set;}
  public String newPointsBucketName {get; set;}
  public List<SelectOption> transferFromList;
  public List<SelectOption> transferToList;
  public String transferFromSelection {get; set;}  
  public String transferToSelection {get; set;}    
 
  String transferredPointsRecordTypeId = Game_Settings__c.getInstance().Transferred_Points_RecordTypeId__c;
  String earnedPointsRecordTypeId = Game_Settings__c.getInstance().Earned_Points_RecordTypeId__c;
  String companyStoreId = Game_Settings__c.getInstance().Company_Store_TargetRecordId__c;
  
  public PointsSummaryController() { 

    proxyPoints = new Points__c();

    // URL parameter may specify a particular user for the "Appirian" lookup
    proxyPoints.User__c = ApexPages.CurrentPage().getParameters().get('userId');
  
    // otherwise, lookup should default to the current user
    if (proxyPoints.User__c == null) proxyPoints.User__c = UserInfo.getUserId();
    
    // if showing the current user's points, or if the user as the right security permission, show the "Remove" button
    if (proxyPoints.User__c == UserInfo.getUserId() || Game_Security__c.getInstance().Remove_Points__c == true) {
      canRemovePoints = true;
    } else {
      canRemovePoints = false;
    } 
    
    User selectedUser = [SELECT Id, 
                                Name, 
                                Direct_Deposit_Points_Into_Company_Store__c 
                         FROM   User 
                         WHERE  Id = :proxyPoints.User__c];
       
    //set the initial values for the transfer points section
    //call the method that builds the values for the 'from' drop down
    populateTransferFromList();
    
    //populate the 'to' drop down with the preliminary options
    transferToList = new List<SelectOption>();
    transferToList.add(new SelectOption('-1', '--SELECT--'));
    
    //set the 'create new points bucket' option field to hidden
    showNewPointsBucketName = false;   
    
    //set the new Points Bucket name
    newPointsBucketName = selectedUser.Name + ' - Shareable Points'; 
    
    //set the transfer amount to 0
    transferAmount = 0;
    
    
  }
  
  
  public String getDirectDepositPointsIntoCompanyStore() {
  
    //set the checkbox for the auto transfer
    //directDepositPointsIntoCompanyStore = 'Automatically every month';
    
    String result = 'Automatically every month';
    
    User selectedUser = [SELECT Id, Direct_Deposit_Points_Into_Company_Store__c from User WHERE Id = :proxyPoints.User__c];
    
    //determine if the Direct Deposit into Company Store needs to be displayed as switched off
    if (!selectedUser.Direct_Deposit_Points_Into_Company_Store__c) {
      //directDepositPointsIntoCompanyStore = 'Manual';
      result = 'Manual';
    }
  
    return result;
  }
  
  public String userDetailLink() {
  
    return URL.getSalesforceBaseUrl().toExternalForm() + '/' + UserInfo.getUserId() +  '?noredirect=1';
  
  }
  
  //get all the points buckets that the user can transfer points to/from
  //user can only transfer points to/from Points Bucket that has been created by that user
  public List<Points_Bucket__c> getPointsBuckets() {
    List<Points_Bucket__c> pointsBucket = [SELECT Id,
                                                  Name,
                                                  Title__c,
                                                  Current_Balance__c
                                           FROM   Points_Bucket__c
                                           WHERE  Owner__c = :proxyPoints.User__c
                                           AND    CreatedById = :proxyPoints.User__c];
  
    return pointsBucket;
  }
  
  
  //creates the drop down list for the transfer 'from' option
  
  public List<SelectOption> getTransferFromList() {
  
    populateTransferFromList();
    return transferFromList;
  
  }
  
  public void populateTransferFromList() {
  
    List<Points_Bucket__c> pointsBucket = getPointsBuckets();
                                           
    transferFromList = new List<SelectOption>();
    
    transferFromList.add(new SelectOption('-1', '--SELECT--'));
    transferFromList.add(new SelectOption('earnedPoints', 'Earned Points'));
            
    for(Points_Bucket__c pb : pointsBucket)
    {
      transferFromList.add(new SelectOption(pb.Name, 'Points Bucket - ' + pb.Title__c + ' (' + pb.Current_Balance__c + ' balance)'));
    }                                         
  }
  
  
  public List<SelectOption> getTransferToList() {
  
    populateTransferToList();
    return transferToList;
  
  }
  
  //creates the drop down list for the transfer 'to' option based on user's
  //selection of the transfer 'from' drop down
  public void populateTransferToList() {
    
    transferToList = new List<SelectOption>();
    List<Points_Bucket__c> pointsBucket = getPointsBuckets();
    
    system.debug('points bucket from list: ' + transferFromList);
    
    transferToList.add(new SelectOption('-1', '--SELECT--'));
    
    if (transferFromSelection != null && transferFromSelection.subString(0,2) != 'PB') {
      transferToList.add(new SelectOption('companyStore', 'Company Store'));
    }
  
    for(SelectOption so : transferFromList) {
      if (so.getValue() != transferFromSelection && so.getValue() != '-1') {
        transferToList.add(so);
      } 
    }
        
    if (pointsBucket.size() == 0) {
      transferToList.add(new SelectOption('-2', '--------------------------'));
      transferToList.add(new SelectOption('new', 'Points Bucket - Create New'));
    }
  }
  
  
  public void displayCreatePointsBucketTextField() {
  
    if (transferToSelection == 'new') {
      showNewPointsBucketName = true;
    }else {
      showNewPointsBucketName = false;
    }
  }
  
  
  private List<Challenge__c> getChallengesForNewPointsBucket() {
  
    String challengeNames = Game_Settings__c.getInstance().Chatter_Challenges_For_Points_Bucket__c.remove(' ');
    
    List<String> challengeNameParts = challengeNames.split(',');
  
    List<Challenge__c> chatterChallenges = [SELECT Id 
                                            FROM   Challenge__c 
                                            WHERE  Name in :challengeNameParts];
                                            
    system.debug('chatter challenges: ' + chatterChallenges);
    
    return chatterChallenges;
  }
  
  public List<AgeUserPointsSummary> getPoints() {
  
    system.debug('setting points');
    
    List<AgeUserPointsSummary> uiPoints = new List<AgeUserPointsSummary>();
    
    List<Points__c> points = [SELECT   Id,
                                       Name,
                                       Challenge__r.Title__c,
                                       Challenge__r.Name,
                                       Amount__c,
                                       Date__c,
                                       Source__c,
                                       Tag__c,
                                       Notes__c,
                                       RecordTypeId,
                                       Entered_In_Company_Store__c,
                                       Status__c,
                                       CreatedDate,
                                       Target_Record_Id__c
                              FROM     Points__c
                              WHERE    User__r.Id = :proxyPoints.User__c
                              ORDER BY CreatedDate DESC];
                  
    pointsEarnedTotal = 0;
    pointsTransferredToCompanyStoreTotal = 0;
    pointsTransferredToPointsBucketsTotal = 0;    
    pointsEarnedThisQuarter = 0;
    pointsBalance = 0;
    
    for (Points__c p : points) {
    
      AgeUserPointsSummary newUiPoint = new AgeUserPointsSummary(CanRemovePoints);
      newUiPoint.Id = p.Id;
      newUiPoint.Name = p.Name;
      newUiPoint.ChallengeTitle = p.Challenge__r.Title__c;
      newUiPoint.Amount = p.Amount__c;
      newUiPoint.ChallengeDate = p.Date__c;
      newUiPoint.CreatedDate = p.CreatedDate;
      newUiPoint.Notes = p.Notes__c;
      newUiPoint.Tag = p.Tag__c;
      newUiPoint.Status = p.Status__c;
      newUiPoint.RecordTypeId = p.RecordTypeId;
                                             
      uiPoints.add(newUiPoint);                                       
    

    
      //add up all earned points record type    
      if (p.Amount__c > 0 && p.RecordTypeId == earnedPointsRecordTypeId) {
        pointsEarnedTotal += p.Amount__c;
      }
      
      //figure out how many company store transfer points to subtract from total available points
      if (p.Amount__c > 0 && p.RecordTypeId == transferredPointsRecordTypeId && p.Target_Record_Id__c == companyStoreId) {
        pointsTransferredToCompanyStoreTotal -= p.Amount__c;
      }
      
      //figure out how many points bucket transfer points to subtract from total available points
      if (p.Amount__c > 0 && p.RecordTypeId == transferredPointsRecordTypeId && p.Target_Record_Id__c.substring(0,2) == 'PB') {
        pointsTransferredToPointsBucketsTotal -= p.Amount__c;
      }      
      
      //figure out how many points were transferred back into earned points from points buckets
      //when a transfer point record has a target record id of earned points, we know that the user transferred points from
      //his/her points bucket into earned points
      if (p.Amount__c > 0 && p.RecordTypeId == transferredPointsRecordTypeId && p.Target_Record_Id__c == earnedPointsRecordTypeId) {
        pointsTransferredToPointsBucketsTotal += p.Amount__c;
      
      }
      if (p.Amount__c > 0 && thisQuarter(p.Date__c) && p.RecordTypeId == earnedPointsRecordTypeId) {
        pointsEarnedThisQuarter += p.Amount__c;
      }
     
    }
    
    
    pointsBalance = pointsEarnedTotal + pointsTransferredToCompanyStoreTotal + pointsTransferredToPointsBucketsTotal;
    
    system.debug('pointsBalance: ' + pointsBalance);
    
    // refresh canRemovePoints, since we may be showing a different user now
    if (proxyPoints.User__c == UserInfo.getUserId() || Game_Security__c.getInstance().Remove_Points__c == true) {
      canRemovePoints = true;
    } else {
      canRemovePoints = false;
    }
    
                                  
    return uiPoints;                              
  }
  
  public class PointsSummaryException extends Exception {}
  
  public PageReference transferPoints() {
  
    System.debug('transferring points');
    
    List<Points_Bucket__c> pointsBucketsToUpdate = new List<Points_Bucket__c>();
    List<Points__c> pointsToInsert = new List<Points__c>();
    Points__c point = new Points__c();
    
    try {
    
      system.debug('transferFromSelection ' + transferFromSelection.subString(0,2));
      system.debug('transferFromSelection ' + transferFromSelection);      
      system.debug('transferToSelection ' + transferToSelection.subString(0,2));
      system.debug('transferToSelection ' + transferToSelection);      
      
      
      //figure out transfer logic if the user's from selection is earned points
      if (transferFromSelection == 'earnedPoints') {
        
        //make sure user has enough points to complete the transfer
        if (pointsBalance < transferAmount) {
          throw new PointsSummaryException('Not enough earned points to transfer');
        }
      
        String notesText = 'Transferred from Earned Points to ';
        
        system.debug('transfer from earned points');
        
        //create a transfer point record
        point.Amount__c = transferAmount;
        point.RecordTypeId = transferredPointsRecordTypeId;
        point.Source__c = 'Points Transfer';
        point.User__c = proxyPoints.User__c;  
        
        if (transferToSelection == 'companyStore') {
          notesText += 'Company Store';
          point.Target_Record_Id__c = companyStoreId;
          point.Status__c = 'Pending';
          
        }else if (transferToSelection.subString(0,2) == 'PB') {
          
          Points_Bucket__c transferTo = [SELECT Id, 
                                                Name,
                                                Current_Balance__c 
                                         FROM   Points_Bucket__c 
                                         WHERE  Name = :transferToSelection];
                                         
          notesText += 'Points Bucket ' + transferTo.Name;
          point.Target_Record_Id__c = transferTo.Name;                                         
                                         
          transferTo.Current_Balance__c = transferTo.Current_Balance__c + transferAmount;
          pointsBucketsToUpdate.add(transferTo); 
          
        }else if (transferToSelection == 'new') {
          Points_Bucket__c newPointsBucket = new Points_Bucket__c(Title__c = newPointsBucketName, 
                                                                  Current_Balance__c = transferAmount,
                                                                  Owner__c = proxyPoints.User__c);                                                            
                                                           
          try{                                                        
            insert newPointsBucket;
          }catch (Exception e){
            insert new Log_Message__c(Message__c = e.getMessage(), Type__c = 'Points Summary Controller');  
          }
          
          Points_Bucket__c justCreatedPB = [SELECT Id, 
                                                   Name 
                                            FROM   Points_Bucket__c 
                                            WHERE  Title__c = :newPointsBucketName
                                            AND    Owner__c = :proxyPoints.User__c];
                                            
          
          List<Challenge__c> chatterChallenges = getChallengesForNewPointsBucket();
          
          List<Challenge_Points_Bucket__c> challengePointsBucketsList = new List<Challenge_Points_Bucket__c>();
          
          for(Challenge__c c : chatterChallenges) {
            
            Challenge_Points_Bucket__c cpb = new Challenge_Points_Bucket__c();
            cpb.Challenge__c = c.Id;
            cpb.Points_Bucket__c = justCreatedPB.Id;
            
            challengePointsBucketsList.add(cpb);
            
          }
          
          insert challengePointsBucketsList;
          
          notesText += 'Shareable Points ' + justCreatedPB.Name;
          point.Target_Record_Id__c = justCreatedPB.Name;
        }
        
        point.Notes__c = notesText;     
          
        system.debug('points object: ' + point);
        
        pointsToInsert.add(point);      
      }


      //figure out transfer logic if the user's from selection is a points bucket
      if (transferFromSelection.subString(0,2) == 'PB') {
        System.debug('transferring from points bucket');
        
        Points_Bucket__c transferFrom = [SELECT Id, 
                                                Current_Balance__c 
                                         FROM   Points_Bucket__c 
                                         WHERE  Name = :transferFromSelection];
        
        //make sure the user's points bucket has enough points to complete the transfer                                 
        if (transferFrom.Current_Balance__c < transferAmount) {
          throw new PointsSummaryException('Not enough points in Points Bucket to transfer');
        }                                         
                                         
        transferFrom.Current_Balance__c = transferFrom.Current_Balance__c - transferAmount;
        
        System.debug('Transfer Points Buckets From: ' + transferFrom);
        pointsBucketsToUpdate.add(transferFrom);  

        //figure out the 'to' selection logic
        if (transferToSelection.subString(0,2) == 'PB') {
          System.debug('transferring to points bucket');
        
          Points_Bucket__c transferTo = [SELECT Id, 
                                                Current_Balance__c 
                                         FROM   Points_Bucket__c 
                                         WHERE  Name = :transferToSelection];
                                         
          transferTo.Current_Balance__c = transferTo.Current_Balance__c + transferAmount;
          pointsBucketsToUpdate.add(transferTo);  
        
        }else if(transferToSelection == 'earnedPoints') {
          system.debug('transfer to earned points');
          
          point.Amount__c = transferAmount;
          point.RecordTypeId = transferredPointsRecordTypeId;
          point.Notes__c = 'Transferred from Points Bucket ' + transferFromSelection.subString(0,7) + ' to Earned Points';
          point.User__c = proxyPoints.User__c;
          point.Target_Record_Id__c = earnedPointsRecordTypeId;
          point.Source__c = 'Points Transfer';
          
          system.debug('points object: ' + point);
        
          pointsToInsert.add(point);      
        }
      } 
      
      system.debug('points bucket to update: ' + pointsBucketsToUpdate); 
      System.debug('points bucket update list: ' + pointsBucketsToUpdate);
      System.debug('points to insert: ' + pointsToInsert);
      
      if (pointsBucketsToUpdate.size() > 0) {
        system.debug('calling dml update for points buckets');
        update pointsBucketsToUpdate;
      }  
      
      if (pointsToInsert.size() > 0) {
        system.debug('calling dml update for points');
        insert pointsToInsert;
        system.debug('done inserting points');
      }      
      
      System.debug('calling filter to redo the drop downs');
      ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'Transfer successful!'));
      populateTransferFromList();
      populateTransferToList();
      showNewPointsBucketName = false;
      transferAmount = 0;
    
    } catch (Exception e) {
      ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));    
    }
  
    return null;
  }
  
  public List<Awarded_Badge__c> getBadges() {
  
  system.debug('====>proxypoints=' + proxyPoints);
  
    List<Awarded_Badge__c> badges = [SELECT   Id,
                                              Name,
                                              Badge__c,
                                              Badge_Title__c,
                                              Effective_Date__c,
                                              CreatedDate
                                     FROM     Awarded_Badge__c
                                     WHERE    User__r.Id = :proxyPoints.User__c
                                     ORDER BY CreatedDate DESC];
    return badges;
  }
  
  public PageReference removePoints() {
  
    try {

      // get Points record name, for display after deletion
      String pointsName = [SELECT Name 
                           FROM   Points__c 
                           WHERE  Id = :selectedPointsId][0].Name;

      delete [SELECT Id
              FROM   Points__c
              WHERE  Id = :selectedPointsId];
              
      ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'Points record ' + pointsName + ' removed.'));

    } catch (Exception e) {
      ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));
    }
          
    // simply refresh page, so list updates itself, and user sees Apex Message  
    return null;
  }

  public PageReference removeBadge() {
  
    try {

      // get Points record name, for display after deletion
      String badgeName = [SELECT Name 
                          FROM   Awarded_Badge__c 
                          WHERE  Id = :selectedBadgeId][0].Name;

      delete [SELECT Id
              FROM   Awarded_Badge__c
              WHERE  Id = :selectedBadgeId];
              
      ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'Badge record ' + badgeName + ' removed.'));

    } catch (Exception e) {
      ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));
    }
          
    // simply refresh page, so list updates itself, and user sees Apex Message  
    return null;
  }
  
  public boolean thisQuarter(Date d) {
  
    if (d == null) return false;
    if (d.year() != Date.today().year()) return false;
    
    Integer thisMonth = Date.today().month();
    Integer targetMonth = d.month();
    
    if (thisMonth >= 1 && thisMonth <= 3) {
      if (targetMonth >= 1 && targetMonth <= 3) {
        return true;
      } else {
        return false;
      }  
    }
 
     if (thisMonth >= 4 && thisMonth <= 6) {
      if (targetMonth >= 4 && targetMonth <= 6) {
        return true;
      } else {
        return false;
      }  
    }

    if (thisMonth >= 7 && thisMonth <= 9) {
      if (targetMonth >= 7 && targetMonth <= 9) {
        return true;
      } else {
        return false;
      }  
    }

    if (thisMonth >= 10 && thisMonth <= 12) {
      if (targetMonth >= 10 && targetMonth <= 12) {
        return true;
      } else {
        return false;
      }  
    }
  
    // it should be impossible to get this far, but I'll still return a value now, to avoid
    // a compile-time warning about "Non-void method might not return a value"
    return false;
   
  }
  
  public PageReference refresh() {
    return null;
  }
  
  public class AgeUserPointsSummary{
  
    public String Id {get; set;}
    public String Name {get; set;}
    public String ChallengeTitle {get; set;}
    public String ChallengeName {get; set;}
    public Decimal Amount {get; set;}
    public Date ChallengeDate {get; set;}
    public String Tag {get; set;}
    public String Notes {get; set;}
    public Boolean EnteredInCompanyStore {get; set;}
    public String Status {get; set;}
    public DateTime CreatedDate {get; set;}
    public String Target_Record_Id {get; set;}
    public String RecordTypeId {get; set;}
    public Boolean CanRemovePoints {get; set;}
    
    String transferredPointsRecordTypeId = Game_Settings__c.getInstance().Transferred_Points_RecordTypeId__c;
  
    
    public AgeUserPointsSummary(Boolean userCanRemovePoints){
      CanRemovePoints = userCanRemovePoints;
    }
    
    public String getSource(){
    
      if (ChallengeTitle != null) {
        return 'Challenge Awarded: ' + ChallengeTitle;
      }else {
        return 'Points Transfer';
      }
    }
    
    public Boolean getShowRemoveButton() {
    
      Boolean canRemove = false;
      
      //transfer records that are pending can be removed.  All other transfers can not be removed
      if (RecordTypeId == transferredPointsRecordTypeId && Status == 'Pending' && CanRemovePoints) {
        canRemove = true;
      //all earned points can be removed  
      }else if(RecordTypeId != transferredPointsRecordTypeId && CanRemovePoints) {
        canRemove = true;
      }
      
      return canRemove;
    
    }

  }
}